//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP223_Egurnova
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartofTovari
    {
        public int ID_cartoftovari { get; set; }
        public int ID_cart { get; set; }
        public int ID_tovar { get; set; }
        public int Quantity { get; set; }
    
        public virtual Carts Carts { get; set; }
        public virtual Tovari Tovari { get; set; }
    }
}
