//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP223_Egurnova
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupPoint
    {
        public int ID_PickupPoint { get; set; }
        public string Name { get; set; }
    }
}
